FROM gradle:8.10.1-jdk21 AS build

WORKDIR /app

COPY . /app
RUN gradle clean build -x test --no-daemon

FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/build/libs/*.jar /app/backend.jar

EXPOSE 8080

ENTRYPOINT ["java"]
CMD ["-jar", "backend.jar"]
