services:
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: local

  db:
    container_name: db
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: capstone
      MYSQL_USER: dev_capstone
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-time-zone='+09:00'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: