services:
  spring-app:
    container_name: spring-app
    image: "noraknorak/backend:latest"
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: capstone
      MYSQL_USER: dev_capstone
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: